import type { Metadata } from 'next';

import '@/app/shared/styles/globals.css';
import '@/app/shared/styles/reset.css';
import 'highlight.js/styles/github-dark.css';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.variable} lang="ko">
      <body className={`font-sans antialiased`}>
        <main className="flex min-h-screen flex-col bg-background">{children}</main>
      </body>
    </html>
  );
}
